// seed/seedData.js
// ------------------------------------------------------------------
// Run with: npm run seed
// Wipes existing Restaurant/FoodItem/User data and inserts sample
// demo data — 20 restaurants and 100 food items — so you can
// explore the app with a realistic amount of content. This project
// intentionally uses fake sample data instead of scraping Swiggy or
// Zomato (as required — no scraping/private APIs).
// ------------------------------------------------------------------

require("dotenv").config();
const mongoose = require("mongoose");
const connectDB = require("../config/db");

const User = require("../models/User");
const Restaurant = require("../models/Restaurant");
const FoodItem = require("../models/FoodItem");

const run = async () => {
  await connectDB();

  console.log("🧹 Clearing existing data...");
  await User.deleteMany();
  await Restaurant.deleteMany();
  await FoodItem.deleteMany();

  console.log("👤 Creating admin + demo user...");
  await User.create({
    name: "Admin",
    email: "admin@foodcompare.com",
    password: "admin123",
    role: "admin",
  });
  await User.create({
    name: "Demo User",
    email: "user@foodcompare.com",
    password: "user1234",
    role: "user",
  });

  console.log("🏬 Creating restaurants...");
  const restaurants = await Restaurant.insertMany([
  {
    name: "Pizza Paradise",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500",
    address: "MG Road, Bengaluru",
    rating: 4.0,
    deliveryTime: "20-35 mins",
    categories: ["Pizza", "Italian"],
  },
  {
    name: "Burger Barn",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
    address: "Andheri West, Mumbai",
    rating: 4.5,
    deliveryTime: "25-40 mins",
    categories: ["Burger", "Fast Food"],
  },
  {
    name: "Spice Villa",
    image: "https://images.unsplash.com/photo-1517244683847-7456b63c5969?w=500",
    address: "Sector 18, Delhi",
    rating: 4.4,
    deliveryTime: "30-45 mins",
    categories: ["Biryani", "North Indian"],
  },
  {
    name: "Sweet Tooth Bakery",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500",
    address: "Park Street, Kolkata",
    rating: 4.3,
    deliveryTime: "35-50 mins",
    categories: ["Dessert", "Bakery"],
  },
  {
    name: "Dragon Wok",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=500",
    address: "Banjara Hills, Hyderabad",
    rating: 4.0,
    deliveryTime: "40-55 mins",
    categories: ["Chinese", "Asian"],
  },
  {
    name: "South Spice Kitchen",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=500",
    address: "T Nagar, Chennai",
    rating: 4.6,
    deliveryTime: "20-35 mins",
    categories: ["South Indian", "Vegetarian"],
  },
  {
    name: "Tandoori Nights",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=500",
    address: "Koregaon Park, Pune",
    rating: 4.6,
    deliveryTime: "25-40 mins",
    categories: ["North Indian", "Mughlai"],
  },
  {
    name: "Coastal Curry House",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    address: "Ring Road, Nellore",
    rating: 4.3,
    deliveryTime: "30-45 mins",
    categories: ["Seafood", "South Indian"],
  },
  {
    name: "Cafe Continental",
    image: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=500",
    address: "Gachibowli, Bengaluru",
    rating: 4.3,
    deliveryTime: "35-50 mins",
    categories: ["Continental", "Cafe"],
  },
  {
    name: "Biryani House",
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500",
    address: "Salt Lake, Mumbai",
    rating: 4.0,
    deliveryTime: "40-55 mins",
    categories: ["Biryani", "Hyderabadi"],
  },
  {
    name: "Green Leaf Vegan",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    address: "MG Road, Delhi",
    rating: 3.8,
    deliveryTime: "20-35 mins",
    categories: ["Vegan", "Healthy"],
  },
  {
    name: "Taco Fiesta",
    image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=500",
    address: "Andheri West, Kolkata",
    rating: 4.2,
    deliveryTime: "25-40 mins",
    categories: ["Mexican"],
  },
  {
    name: "Noodle Street",
    image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?w=500",
    address: "Sector 18, Hyderabad",
    rating: 4.4,
    deliveryTime: "30-45 mins",
    categories: ["Thai", "Asian"],
  },
  {
    name: "Punjabi Dhaba",
    image: "https://images.unsplash.com/photo-1555126634-323283e090fa?w=500",
    address: "Park Street, Chennai",
    rating: 3.9,
    deliveryTime: "35-50 mins",
    categories: ["North Indian", "Punjabi"],
  },
  {
    name: "Royal Kebab Corner",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    address: "Banjara Hills, Pune",
    rating: 4.6,
    deliveryTime: "40-55 mins",
    categories: ["Mughlai", "North Indian"],
  },
  {
    name: "Momo Magic",
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=500",
    address: "T Nagar, Nellore",
    rating: 4.0,
    deliveryTime: "20-35 mins",
    categories: ["Tibetan", "Momos"],
  },
  {
    name: "Health Bowl Cafe",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500",
    address: "Koregaon Park, Bengaluru",
    rating: 4.0,
    deliveryTime: "25-40 mins",
    categories: ["Healthy", "Salads"],
  },
  {
    name: "The Sandwich Stop",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
    address: "Ring Road, Mumbai",
    rating: 3.8,
    deliveryTime: "30-45 mins",
    categories: ["Sandwiches", "Fast Food"],
  },
  {
    name: "Chettinad Spice",
    image: "https://images.unsplash.com/photo-1517244683847-7456b63c5969?w=500",
    address: "Gachibowli, Delhi",
    rating: 4.8,
    deliveryTime: "35-50 mins",
    categories: ["South Indian", "Chettinad"],
  },
  {
    name: "Bengali Sweets House",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500",
    address: "Salt Lake, Kolkata",
    rating: 4.5,
    deliveryTime: "40-55 mins",
    categories: ["Dessert", "Bengali"],
  },
  ]);

  const [r0, r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12, r13, r14, r15, r16, r17, r18, r19] = restaurants;

  console.log("🍔 Creating food items...");
  await FoodItem.insertMany([
  {
    name: "Margherita Pizza",
    restaurant: r0._id,
    category: "Pizza",
    description: "Classic cheese & tomato pizza on a thin crust.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500",
    swiggyPrice: 258,
    zomatoPrice: 233,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.6,
  },
  {
    name: "Farmhouse Pizza",
    restaurant: r0._id,
    category: "Pizza",
    description: "Loaded with capsicum, onion, tomato & mushroom.",
    image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=500",
    swiggyPrice: 356,
    zomatoPrice: 374,
    offers: { swiggy: "Free delivery", zomato: "15% OFF up to ₹60" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.5,
  },
  {
    name: "Pepperoni Pizza",
    restaurant: r0._id,
    category: "Pizza",
    description: "Double pepperoni with mozzarella.",
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=500",
    swiggyPrice: 400,
    zomatoPrice: 379,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.8,
  },
  {
    name: "Paneer Tikka Pizza",
    restaurant: r0._id,
    category: "Pizza",
    description: "Tandoori paneer chunks with peppers.",
    image: "https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=500",
    swiggyPrice: 371,
    zomatoPrice: 352,
    offers: { swiggy: "25% OFF up to ₹80", zomato: "Flat ₹60 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.7,
  },
  {
    name: "BBQ Chicken Pizza",
    restaurant: r0._id,
    category: "Pizza",
    description: "Smoky BBQ chicken with red onions.",
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=500",
    swiggyPrice: 433,
    zomatoPrice: 444,
    offers: { swiggy: "10% OFF up to ₹50", zomato: "Flat ₹40 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.3,
  },
  {
    name: "Classic Cheeseburger",
    restaurant: r1._id,
    category: "Burger",
    description: "Juicy patty with cheddar cheese and fresh veggies.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
    swiggyPrice: 151,
    zomatoPrice: 144,
    offers: { swiggy: "Free delivery", zomato: "15% OFF up to ₹60" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.8,
  },
  {
    name: "Double Patty Burger",
    restaurant: r1._id,
    category: "Burger",
    description: "Two beef-style patties, double cheese.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
    swiggyPrice: 220,
    zomatoPrice: 224,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.7,
  },
  {
    name: "Aloo Tikki Burger",
    restaurant: r1._id,
    category: "Burger",
    description: "Crispy potato patty, mint chutney.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
    swiggyPrice: 91,
    zomatoPrice: 103,
    offers: { swiggy: "20% OFF up to ₹100", zomato: "Buy 1 Get 1" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.9,
  },
  {
    name: "Mushroom Burger",
    restaurant: r1._id,
    category: "Burger",
    description: "Grilled mushroom and swiss cheese.",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500",
    swiggyPrice: 194,
    zomatoPrice: 180,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.6,
  },
  {
    name: "Grilled Chicken Burger",
    restaurant: r1._id,
    category: "Burger",
    description: "Char-grilled chicken breast, lettuce.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
    swiggyPrice: 207,
    zomatoPrice: 202,
    offers: { swiggy: "25% OFF up to ₹80", zomato: "Flat ₹60 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.7,
  },
  {
    name: "Chicken Biryani",
    restaurant: r2._id,
    category: "Biryani",
    description: "Fragrant basmati rice slow-cooked with spiced chicken.",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=500",
    swiggyPrice: 304,
    zomatoPrice: 286,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.7,
  },
  {
    name: "Mutton Biryani",
    restaurant: r2._id,
    category: "Biryani",
    description: "Slow-cooked mutton with saffron rice.",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=500",
    swiggyPrice: 399,
    zomatoPrice: 373,
    offers: { swiggy: "20% OFF up to ₹100", zomato: "Buy 1 Get 1" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.8,
  },
  {
    name: "Veg Biryani",
    restaurant: r2._id,
    category: "Biryani",
    description: "Mixed vegetables in aromatic basmati rice.",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=500",
    swiggyPrice: 218,
    zomatoPrice: 200,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.8,
  },
  {
    name: "Egg Biryani",
    restaurant: r2._id,
    category: "Biryani",
    description: "Boiled eggs tossed in spiced rice.",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=500",
    swiggyPrice: 231,
    zomatoPrice: 219,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.9,
  },
  {
    name: "Hyderabadi Biryani",
    restaurant: r2._id,
    category: "Biryani",
    description: "The original dum-cooked classic.",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=500",
    swiggyPrice: 327,
    zomatoPrice: 339,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.7,
  },
  {
    name: "Chocolate Truffle Cake",
    restaurant: r3._id,
    category: "Dessert",
    description: "Rich chocolate sponge with silky ganache.",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500",
    swiggyPrice: 411,
    zomatoPrice: 461,
    offers: { swiggy: "20% OFF up to ₹100", zomato: "Buy 1 Get 1" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.9,
  },
  {
    name: "Gulab Jamun (4 pcs)",
    restaurant: r3._id,
    category: "Dessert",
    description: "Soft milk dumplings in rose syrup.",
    image: "https://images.unsplash.com/photo-1601303516361-6ce4c95c6a55?w=500",
    swiggyPrice: 89,
    zomatoPrice: 94,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.7,
  },
  {
    name: "Red Velvet Pastry",
    restaurant: r3._id,
    category: "Dessert",
    description: "Cream cheese frosted red velvet slice.",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500",
    swiggyPrice: 162,
    zomatoPrice: 145,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.9,
  },
  {
    name: "Rasmalai (4 pcs)",
    restaurant: r3._id,
    category: "Dessert",
    description: "Cottage cheese dumplings in saffron milk.",
    image: "https://images.unsplash.com/photo-1601303516361-6ce4c95c6a55?w=500",
    swiggyPrice: 129,
    zomatoPrice: 126,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.9,
  },
  {
    name: "Brownie with Ice Cream",
    restaurant: r3._id,
    category: "Dessert",
    description: "Warm brownie, vanilla scoop.",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500",
    swiggyPrice: 174,
    zomatoPrice: 210,
    offers: { swiggy: "10% OFF up to ₹50", zomato: "Flat ₹40 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.8,
  },
  {
    name: "Veg Hakka Noodles",
    restaurant: r4._id,
    category: "Chinese",
    description: "Stir-fried noodles with julienned veggies.",
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500",
    swiggyPrice: 179,
    zomatoPrice: 170,
    offers: { swiggy: "Free delivery", zomato: "15% OFF up to ₹60" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.6,
  },
  {
    name: "Chilli Chicken",
    restaurant: r4._id,
    category: "Chinese",
    description: "Indo-Chinese wok-tossed chicken.",
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500",
    swiggyPrice: 246,
    zomatoPrice: 232,
    offers: { swiggy: "Free delivery", zomato: "15% OFF up to ₹60" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.8,
  },
  {
    name: "Chicken Manchurian",
    restaurant: r4._id,
    category: "Chinese",
    description: "Fried chicken balls in tangy sauce.",
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500",
    swiggyPrice: 254,
    zomatoPrice: 263,
    offers: { swiggy: "25% OFF up to ₹80", zomato: "Flat ₹60 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.2,
  },
  {
    name: "Schezwan Fried Rice",
    restaurant: r4._id,
    category: "Chinese",
    description: "Spicy schezwan-tossed rice.",
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500",
    swiggyPrice: 200,
    zomatoPrice: 170,
    offers: { swiggy: "20% OFF up to ₹100", zomato: "Buy 1 Get 1" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.5,
  },
  {
    name: "Honey Chilli Potato",
    restaurant: r4._id,
    category: "Chinese",
    description: "Crispy potato in sweet-spicy glaze.",
    image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=500",
    swiggyPrice: 156,
    zomatoPrice: 152,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.8,
  },
  {
    name: "Masala Dosa",
    restaurant: r5._id,
    category: "South Indian",
    description: "Crispy rice crepe with spiced potato filling.",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500",
    swiggyPrice: 112,
    zomatoPrice: 97,
    offers: { swiggy: "20% OFF up to ₹100", zomato: "Buy 1 Get 1" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.6,
  },
  {
    name: "Idli Sambar (4 pcs)",
    restaurant: r5._id,
    category: "South Indian",
    description: "Steamed rice cakes with lentil sambar.",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500",
    swiggyPrice: 84,
    zomatoPrice: 75,
    offers: { swiggy: "Free delivery", zomato: "15% OFF up to ₹60" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.1,
  },
  {
    name: "Medu Vada (2 pcs)",
    restaurant: r5._id,
    category: "South Indian",
    description: "Crispy lentil doughnuts.",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500",
    swiggyPrice: 66,
    zomatoPrice: 54,
    offers: { swiggy: "20% OFF up to ₹100", zomato: "Buy 1 Get 1" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.3,
  },
  {
    name: "Rava Dosa",
    restaurant: r5._id,
    category: "South Indian",
    description: "Crisp semolina crepe.",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500",
    swiggyPrice: 124,
    zomatoPrice: 102,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.6,
  },
  {
    name: "Uttapam",
    restaurant: r5._id,
    category: "South Indian",
    description: "Thick savoury pancake with onion & tomato.",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500",
    swiggyPrice: 90,
    zomatoPrice: 88,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.7,
  },
  {
    name: "Paneer Butter Masala",
    restaurant: r6._id,
    category: "North Indian",
    description: "Cottage cheese cubes in creamy tomato gravy.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 270,
    zomatoPrice: 258,
    offers: { swiggy: "Free delivery", zomato: "15% OFF up to ₹60" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.6,
  },
  {
    name: "Dal Makhani",
    restaurant: r6._id,
    category: "North Indian",
    description: "Slow-cooked black lentils in butter & cream.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 214,
    zomatoPrice: 211,
    offers: { swiggy: "20% OFF up to ₹100", zomato: "Buy 1 Get 1" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.7,
  },
  {
    name: "Butter Chicken",
    restaurant: r6._id,
    category: "North Indian",
    description: "Tandoori chicken in creamy tomato gravy.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 339,
    zomatoPrice: 303,
    offers: { swiggy: "Free delivery", zomato: "15% OFF up to ₹60" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.9,
  },
  {
    name: "Kadai Paneer",
    restaurant: r6._id,
    category: "North Indian",
    description: "Paneer tossed with peppers in kadai masala.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 262,
    zomatoPrice: 244,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.7,
  },
  {
    name: "Chole Bhature",
    restaurant: r6._id,
    category: "North Indian",
    description: "Spiced chickpeas with fried bread.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 159,
    zomatoPrice: 145,
    offers: { swiggy: "20% OFF up to ₹100", zomato: "Buy 1 Get 1" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.8,
  },
  {
    name: "Fish Curry",
    restaurant: r7._id,
    category: "Seafood",
    description: "Coconut-based coastal fish curry.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    swiggyPrice: 319,
    zomatoPrice: 315,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.8,
  },
  {
    name: "Prawn Masala",
    restaurant: r7._id,
    category: "Seafood",
    description: "Spicy prawns in onion-tomato masala.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    swiggyPrice: 394,
    zomatoPrice: 363,
    offers: { swiggy: "Free delivery", zomato: "15% OFF up to ₹60" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.7,
  },
  {
    name: "Fish Fry",
    restaurant: r7._id,
    category: "Seafood",
    description: "Crispy shallow-fried fish, coastal spices.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    swiggyPrice: 303,
    zomatoPrice: 282,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.2,
  },
  {
    name: "Crab Curry",
    restaurant: r7._id,
    category: "Seafood",
    description: "Whole crab in spicy coastal gravy.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    swiggyPrice: 454,
    zomatoPrice: 428,
    offers: { swiggy: "25% OFF up to ₹80", zomato: "Flat ₹60 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.8,
  },
  {
    name: "Fish Curry",
    restaurant: r7._id,
    category: "Seafood",
    description: "Coconut-based coastal fish curry.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    swiggyPrice: 327,
    zomatoPrice: 313,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.6,
  },
  {
    name: "Grilled Chicken Steak",
    restaurant: r8._id,
    category: "Continental",
    description: "Herb-marinated grilled chicken breast.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    swiggyPrice: 401,
    zomatoPrice: 390,
    offers: { swiggy: "10% OFF up to ₹50", zomato: "Flat ₹40 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.8,
  },
  {
    name: "Pasta Alfredo",
    restaurant: r8._id,
    category: "Continental",
    description: "Creamy white sauce pasta.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    swiggyPrice: 269,
    zomatoPrice: 267,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.4,
  },
  {
    name: "Caesar Salad",
    restaurant: r8._id,
    category: "Continental",
    description: "Romaine, parmesan, croutons, Caesar dressing.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    swiggyPrice: 226,
    zomatoPrice: 227,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.1,
  },
  {
    name: "Grilled Chicken Steak",
    restaurant: r8._id,
    category: "Continental",
    description: "Herb-marinated grilled chicken breast.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    swiggyPrice: 401,
    zomatoPrice: 393,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.8,
  },
  {
    name: "Pasta Alfredo",
    restaurant: r8._id,
    category: "Continental",
    description: "Creamy white sauce pasta.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500",
    swiggyPrice: 273,
    zomatoPrice: 263,
    offers: { swiggy: "20% OFF up to ₹100", zomato: "Buy 1 Get 1" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.7,
  },
  {
    name: "Chicken Biryani",
    restaurant: r9._id,
    category: "Biryani",
    description: "Fragrant basmati rice slow-cooked with spiced chicken.",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=500",
    swiggyPrice: 294,
    zomatoPrice: 269,
    offers: { swiggy: "10% OFF up to ₹50", zomato: "Flat ₹40 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.4,
  },
  {
    name: "Mutton Biryani",
    restaurant: r9._id,
    category: "Biryani",
    description: "Slow-cooked mutton with saffron rice.",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=500",
    swiggyPrice: 393,
    zomatoPrice: 371,
    offers: { swiggy: "25% OFF up to ₹80", zomato: "Flat ₹60 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.7,
  },
  {
    name: "Veg Biryani",
    restaurant: r9._id,
    category: "Biryani",
    description: "Mixed vegetables in aromatic basmati rice.",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=500",
    swiggyPrice: 218,
    zomatoPrice: 193,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.0,
  },
  {
    name: "Egg Biryani",
    restaurant: r9._id,
    category: "Biryani",
    description: "Boiled eggs tossed in spiced rice.",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=500",
    swiggyPrice: 231,
    zomatoPrice: 224,
    offers: { swiggy: "Free delivery", zomato: "15% OFF up to ₹60" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.8,
  },
  {
    name: "Hyderabadi Biryani",
    restaurant: r9._id,
    category: "Biryani",
    description: "The original dum-cooked classic.",
    image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=500",
    swiggyPrice: 324,
    zomatoPrice: 344,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.8,
  },
  {
    name: "Vegan Buddha Bowl",
    restaurant: r10._id,
    category: "Vegan",
    description: "Quinoa, chickpeas, roasted veggies.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    swiggyPrice: 245,
    zomatoPrice: 251,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.6,
  },
  {
    name: "Tofu Stir Fry",
    restaurant: r10._id,
    category: "Vegan",
    description: "Pan-seared tofu with mixed vegetables.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    swiggyPrice: 210,
    zomatoPrice: 218,
    offers: { swiggy: "25% OFF up to ₹80", zomato: "Flat ₹60 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.5,
  },
  {
    name: "Vegan Burger",
    restaurant: r10._id,
    category: "Vegan",
    description: "Plant-based patty, vegan cheese.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    swiggyPrice: 212,
    zomatoPrice: 203,
    offers: { swiggy: "25% OFF up to ₹80", zomato: "Flat ₹60 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.7,
  },
  {
    name: "Vegan Buddha Bowl",
    restaurant: r10._id,
    category: "Vegan",
    description: "Quinoa, chickpeas, roasted veggies.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    swiggyPrice: 251,
    zomatoPrice: 243,
    offers: { swiggy: "10% OFF up to ₹50", zomato: "Flat ₹40 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.7,
  },
  {
    name: "Tofu Stir Fry",
    restaurant: r10._id,
    category: "Vegan",
    description: "Pan-seared tofu with mixed vegetables.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    swiggyPrice: 233,
    zomatoPrice: 217,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.8,
  },
  {
    name: "Chicken Burrito",
    restaurant: r11._id,
    category: "Mexican",
    description: "Grilled chicken, rice, beans, salsa wrap.",
    image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=500",
    swiggyPrice: 226,
    zomatoPrice: 217,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.9,
  },
  {
    name: "Loaded Nachos",
    restaurant: r11._id,
    category: "Mexican",
    description: "Tortilla chips, cheese, jalapenos, salsa.",
    image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=500",
    swiggyPrice: 199,
    zomatoPrice: 202,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.7,
  },
  {
    name: "Veg Quesadilla",
    restaurant: r11._id,
    category: "Mexican",
    description: "Grilled tortilla with cheese and veggies.",
    image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=500",
    swiggyPrice: 173,
    zomatoPrice: 168,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.5,
  },
  {
    name: "Chicken Burrito",
    restaurant: r11._id,
    category: "Mexican",
    description: "Grilled chicken, rice, beans, salsa wrap.",
    image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=500",
    swiggyPrice: 235,
    zomatoPrice: 234,
    offers: { swiggy: "Free delivery", zomato: "15% OFF up to ₹60" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.3,
  },
  {
    name: "Loaded Nachos",
    restaurant: r11._id,
    category: "Mexican",
    description: "Tortilla chips, cheese, jalapenos, salsa.",
    image: "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=500",
    swiggyPrice: 192,
    zomatoPrice: 196,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.4,
  },
  {
    name: "Pad Thai",
    restaurant: r12._id,
    category: "Thai",
    description: "Stir-fried rice noodles, peanuts, lime.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=500",
    swiggyPrice: 258,
    zomatoPrice: 252,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.0,
  },
  {
    name: "Thai Green Curry",
    restaurant: r12._id,
    category: "Thai",
    description: "Coconut curry with vegetables.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=500",
    swiggyPrice: 258,
    zomatoPrice: 248,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.5,
  },
  {
    name: "Tom Yum Soup",
    restaurant: r12._id,
    category: "Thai",
    description: "Hot & sour Thai soup with herbs.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=500",
    swiggyPrice: 193,
    zomatoPrice: 176,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.8,
  },
  {
    name: "Pad Thai",
    restaurant: r12._id,
    category: "Thai",
    description: "Stir-fried rice noodles, peanuts, lime.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=500",
    swiggyPrice: 249,
    zomatoPrice: 235,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.1,
  },
  {
    name: "Thai Green Curry",
    restaurant: r12._id,
    category: "Thai",
    description: "Coconut curry with vegetables.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=500",
    swiggyPrice: 270,
    zomatoPrice: 252,
    offers: { swiggy: "Free delivery", zomato: "15% OFF up to ₹60" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.7,
  },
  {
    name: "Paneer Butter Masala",
    restaurant: r13._id,
    category: "North Indian",
    description: "Cottage cheese cubes in creamy tomato gravy.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 269,
    zomatoPrice: 251,
    offers: { swiggy: "10% OFF up to ₹50", zomato: "Flat ₹40 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.4,
  },
  {
    name: "Dal Makhani",
    restaurant: r13._id,
    category: "North Indian",
    description: "Slow-cooked black lentils in butter & cream.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 233,
    zomatoPrice: 213,
    offers: { swiggy: "25% OFF up to ₹80", zomato: "Flat ₹60 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.3,
  },
  {
    name: "Butter Chicken",
    restaurant: r13._id,
    category: "North Indian",
    description: "Tandoori chicken in creamy tomato gravy.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 340,
    zomatoPrice: 319,
    offers: { swiggy: "10% OFF up to ₹50", zomato: "Flat ₹40 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.5,
  },
  {
    name: "Kadai Paneer",
    restaurant: r13._id,
    category: "North Indian",
    description: "Paneer tossed with peppers in kadai masala.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 255,
    zomatoPrice: 245,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.1,
  },
  {
    name: "Chole Bhature",
    restaurant: r13._id,
    category: "North Indian",
    description: "Spiced chickpeas with fried bread.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 141,
    zomatoPrice: 136,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.6,
  },
  {
    name: "Chicken Rogan Josh",
    restaurant: r14._id,
    category: "Mughlai",
    description: "Slow-cooked Kashmiri-style curry.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 352,
    zomatoPrice: 320,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.9,
  },
  {
    name: "Mutton Kebab (6 pcs)",
    restaurant: r14._id,
    category: "Mughlai",
    description: "Charcoal-grilled minced mutton skewers.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 337,
    zomatoPrice: 321,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.5,
  },
  {
    name: "Shahi Paneer",
    restaurant: r14._id,
    category: "Mughlai",
    description: "Paneer in rich cashew-tomato gravy.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 294,
    zomatoPrice: 266,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.1,
  },
  {
    name: "Chicken Rogan Josh",
    restaurant: r14._id,
    category: "Mughlai",
    description: "Slow-cooked Kashmiri-style curry.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 354,
    zomatoPrice: 326,
    offers: { swiggy: "Free delivery", zomato: "15% OFF up to ₹60" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.4,
  },
  {
    name: "Mutton Kebab (6 pcs)",
    restaurant: r14._id,
    category: "Mughlai",
    description: "Charcoal-grilled minced mutton skewers.",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500",
    swiggyPrice: 321,
    zomatoPrice: 310,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.2,
  },
  {
    name: "Veg Steamed Momos (8 pcs)",
    restaurant: r15._id,
    category: "Tibetan",
    description: "Steamed dumplings with veg filling.",
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=500",
    swiggyPrice: 130,
    zomatoPrice: 131,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.4,
  },
  {
    name: "Chicken Fried Momos (8 pcs)",
    restaurant: r15._id,
    category: "Tibetan",
    description: "Pan-fried chicken dumplings.",
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=500",
    swiggyPrice: 173,
    zomatoPrice: 153,
    offers: { swiggy: "20% OFF up to ₹100", zomato: "Buy 1 Get 1" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.4,
  },
  {
    name: "Paneer Momos (8 pcs)",
    restaurant: r15._id,
    category: "Tibetan",
    description: "Steamed dumplings, paneer filling.",
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=500",
    swiggyPrice: 148,
    zomatoPrice: 140,
    offers: { swiggy: "25% OFF up to ₹80", zomato: "Flat ₹60 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.6,
  },
  {
    name: "Veg Steamed Momos (8 pcs)",
    restaurant: r15._id,
    category: "Tibetan",
    description: "Steamed dumplings with veg filling.",
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=500",
    swiggyPrice: 141,
    zomatoPrice: 130,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.9,
  },
  {
    name: "Chicken Fried Momos (8 pcs)",
    restaurant: r15._id,
    category: "Tibetan",
    description: "Pan-fried chicken dumplings.",
    image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=500",
    swiggyPrice: 164,
    zomatoPrice: 151,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.0,
  },
  {
    name: "Sprouts Salad Bowl",
    restaurant: r16._id,
    category: "Healthy",
    description: "Mixed sprouts, veggies, lemon dressing.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    swiggyPrice: 155,
    zomatoPrice: 151,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.9,
  },
  {
    name: "Grilled Chicken Salad",
    restaurant: r16._id,
    category: "Healthy",
    description: "Grilled chicken, greens, vinaigrette.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    swiggyPrice: 224,
    zomatoPrice: 219,
    offers: { swiggy: "10% OFF up to ₹50", zomato: "Flat ₹40 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.9,
  },
  {
    name: "Fruit & Nut Bowl",
    restaurant: r16._id,
    category: "Healthy",
    description: "Seasonal fruit with mixed nuts.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    swiggyPrice: 161,
    zomatoPrice: 133,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.7,
  },
  {
    name: "Sprouts Salad Bowl",
    restaurant: r16._id,
    category: "Healthy",
    description: "Mixed sprouts, veggies, lemon dressing.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    swiggyPrice: 141,
    zomatoPrice: 145,
    offers: { swiggy: "20% OFF up to ₹100", zomato: "Buy 1 Get 1" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.0,
  },
  {
    name: "Grilled Chicken Salad",
    restaurant: r16._id,
    category: "Healthy",
    description: "Grilled chicken, greens, vinaigrette.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500",
    swiggyPrice: 242,
    zomatoPrice: 232,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.2,
  },
  {
    name: "Club Sandwich",
    restaurant: r17._id,
    category: "Fast Food",
    description: "Triple-layer veg club sandwich.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
    swiggyPrice: 144,
    zomatoPrice: 151,
    offers: { swiggy: "10% OFF up to ₹50", zomato: "Flat ₹40 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.2,
  },
  {
    name: "Grilled Cheese Sandwich",
    restaurant: r17._id,
    category: "Fast Food",
    description: "Melty cheese between grilled bread.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
    swiggyPrice: 99,
    zomatoPrice: 90,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.4,
  },
  {
    name: "French Fries",
    restaurant: r17._id,
    category: "Fast Food",
    description: "Crispy golden fries, peri-peri masala.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
    swiggyPrice: 95,
    zomatoPrice: 87,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.7,
  },
  {
    name: "Club Sandwich",
    restaurant: r17._id,
    category: "Fast Food",
    description: "Triple-layer veg club sandwich.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
    swiggyPrice: 149,
    zomatoPrice: 145,
    offers: { swiggy: "10% OFF up to ₹50", zomato: "Flat ₹40 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.9,
  },
  {
    name: "Grilled Cheese Sandwich",
    restaurant: r17._id,
    category: "Fast Food",
    description: "Melty cheese between grilled bread.",
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=500",
    swiggyPrice: 93,
    zomatoPrice: 100,
    offers: { swiggy: "25% OFF up to ₹80", zomato: "Flat ₹60 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.3,
  },
  {
    name: "Masala Dosa",
    restaurant: r18._id,
    category: "South Indian",
    description: "Crispy rice crepe with spiced potato filling.",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500",
    swiggyPrice: 108,
    zomatoPrice: 101,
    offers: { swiggy: "20% OFF up to ₹100", zomato: "Buy 1 Get 1" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.0,
  },
  {
    name: "Idli Sambar (4 pcs)",
    restaurant: r18._id,
    category: "South Indian",
    description: "Steamed rice cakes with lentil sambar.",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500",
    swiggyPrice: 74,
    zomatoPrice: 71,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.2,
  },
  {
    name: "Medu Vada (2 pcs)",
    restaurant: r18._id,
    category: "South Indian",
    description: "Crispy lentil doughnuts.",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500",
    swiggyPrice: 73,
    zomatoPrice: 68,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.5,
  },
  {
    name: "Rava Dosa",
    restaurant: r18._id,
    category: "South Indian",
    description: "Crisp semolina crepe.",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500",
    swiggyPrice: 104,
    zomatoPrice: 110,
    offers: { swiggy: "Flat ₹50 OFF above ₹250", zomato: "10% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.1,
  },
  {
    name: "Uttapam",
    restaurant: r18._id,
    category: "South Indian",
    description: "Thick savoury pancake with onion & tomato.",
    image: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=500",
    swiggyPrice: 92,
    zomatoPrice: 85,
    offers: { swiggy: "Free delivery", zomato: "15% OFF up to ₹60" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.9,
  },
  {
    name: "Chocolate Truffle Cake",
    restaurant: r19._id,
    category: "Dessert",
    description: "Rich chocolate sponge with silky ganache.",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500",
    swiggyPrice: 390,
    zomatoPrice: 450,
    offers: { swiggy: "20% OFF up to ₹100", zomato: "Buy 1 Get 1" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.7,
  },
  {
    name: "Gulab Jamun (4 pcs)",
    restaurant: r19._id,
    category: "Dessert",
    description: "Soft milk dumplings in rose syrup.",
    image: "https://images.unsplash.com/photo-1601303516361-6ce4c95c6a55?w=500",
    swiggyPrice: 111,
    zomatoPrice: 90,
    offers: { swiggy: "25% OFF up to ₹80", zomato: "Flat ₹60 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.6,
  },
  {
    name: "Red Velvet Pastry",
    restaurant: r19._id,
    category: "Dessert",
    description: "Cream cheese frosted red velvet slice.",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500",
    swiggyPrice: 157,
    zomatoPrice: 130,
    offers: { swiggy: "5% OFF", zomato: "Flat 15% OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 4.1,
  },
  {
    name: "Rasmalai (4 pcs)",
    restaurant: r19._id,
    category: "Dessert",
    description: "Cottage cheese dumplings in saffron milk.",
    image: "https://images.unsplash.com/photo-1601303516361-6ce4c95c6a55?w=500",
    swiggyPrice: 141,
    zomatoPrice: 123,
    offers: { swiggy: "", zomato: "" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.9,
  },
  {
    name: "Brownie with Ice Cream",
    restaurant: r19._id,
    category: "Dessert",
    description: "Warm brownie, vanilla scoop.",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500",
    swiggyPrice: 186,
    zomatoPrice: 193,
    offers: { swiggy: "10% OFF up to ₹50", zomato: "Flat ₹40 OFF" },
    swiggyUrl: "https://www.swiggy.com",
    zomatoUrl: "https://www.zomato.com",
    rating: 3.7,
  },
  ]);

  console.log("✅ Seed data inserted successfully!");
  console.log("   20 restaurants, 100 food items");
  console.log("   Admin login  -> admin@foodcompare.com / admin123");
  console.log("   User login   -> user@foodcompare.com / user1234");

  await mongoose.connection.close();
  process.exit(0);
};

run().catch((err) => {
  console.error("❌ Seeding failed:", err);
  process.exit(1);
});
